version: "3.8"

services:
  madr_mongo:
    image: mongo:7
    container_name: madr_mongo
    ports:
      - "27017:27017"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - mongo_data:/data/db

  madr_app:
    image: madr_app
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - madr_mongo
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo

volumes:
  mongo_data:
